name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PRIMARY_NODE_VERSION: 18

jobs:
  install:
    name: Checkout and Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: ./.github/actions/prepare-install
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}
  lint:
    name: Lint
    needs: [install]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lint-task: ['check-format', 'eslint']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: ./.github/actions/prepare-install
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}

      - name: Run Check
        run: yarn ${{ matrix.lint-task }}
